import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })


export default function Home() {
  return (
    <>
      <Head>
        <title>Hecla</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='flex flex-1 min-h-screen bg-[#026396] items-center justify-center overflow-auto py-20 md:py-0'>

        <div className='flex flex-col w-[85%] justify-between items-center  md:w-[70%] lg:w-[60%]'>

          <div className='flex flex-col items-center mb-10'>
          <h1 className='text-6xl mb-1'>Hecla</h1>
          <h2 className='text-3xl'>Emission Management</h2>
          </div>


          <p className='text-lg mb-5'>Shipping is due to enter the European Emissions Trading System (EU ETS) on the 1st January 2024.</p>

          <p className='text-lg mb-5'>Hecla Emissions Management has been created to assist shipowners and charterers with all the compliance obligations associated with managing the EU ETS. Services include registry account management, data handling and verification, procurement of allowances and annual surrendering.</p>


          <p className='text-lg mb-5 text-[#fffe00]'>Hecla offers a full outsourcing service for shipping customers in the EU ETS</p>

          <p className='text-lg mb-5'>With the EU legal text due to be published within Q1 2023, updates to this site will follow in due course.</p>

          <p className='text-lg mb-5'>In the mean time, please click here if you would like to download our PDF summary on the <a className='underline font-semibold hover:text-[#fffe00] cursor-pointer' href='Hecla_ETS_Summary.pdf' target="_blank">Inclusion of Shipping in the EU ETS</a>.</p> 

          {/* apply @mailto here */}
          <p className='text-lg mb-5'>To find out more, or to speak with one of our team, please email <a className='underline font-semibold hover:text-[#fffe00] cursor-pointer' href="mailto:paolo.viselli@affinityship.com">info@hecla-em.com</a>  </p>
        </div>
      </main>
    </>
  )
}
